export const pagesRoutes = [
  ["v-01560935","/timeline/",{"title":""},[]],
  ["v-e1e3da16","/posts/",{"title":""},[]],
  ["v-53355ebb","/friendship-link/",{"title":""},[]],
  ["v-7cfe6452","/categories/tucao/1/",{"title":""},[]],
  ["v-d537c98e","/categories/manhua/1/",{"title":""},[]],
  ["v-fa649de2","/categories/sheyingji/1/",{"title":""},[]],
  ["v-575e2c28","/tags/richang/1/",{"title":""},[]],
  ["v-94570094","/tags/manhua/1/",{"title":""},[]],
  ["v-55531a85","/tags/TOKYO2023/1/",{"title":""},[]],
  ["v-03d52fd3","/posts/1/",{"title":""},[]],
  ["v-8daa1a0e","/",{"title":""},["/README.md"]],
  ["v-390d5c70","/blogs/article/",{"title":"日常1号"},["/blogs/article/README.md"]],
  ["v-6cc9077c","/blogs/photograph/",{"title":""},["/blogs/photograph/README.md"]],
  ["v-88884ba0","/docs/machine-learning/",{"title":"目录"},["/docs/machine-learning/README.md"]],
  ["v-303ef5c2","/blogs/comic/hsqure/",{"title":"花花作品集"},["/blogs/comic/hsqure/README.md"]],
  ["v-b88d553e","/blogs/comic/others/",{"title":"NICE！推荐系列"},["/blogs/comic/others/README.md"]],
  ["v-79ae11f4","/blogs/photograph/Tokyo2023/",{"title":""},["/blogs/photograph/Tokyo2023/README.md"]],
  ["v-abc79bec","/docs/machine-learning/artificial-general-intelligence/artificial-general-intelligence.html",{"title":"通用人工智能"},[":md"]],
  ["v-e1b41c18","/docs/machine-learning/auto-machine-learning/auto-machine-learning.html",{"title":"AutoML"},[":md"]],
  ["v-5e1316f8","/docs/machine-learning/computer-vision/computer-vision.html",{"title":"前言"},[":md"]],
  ["v-3cbbe28c","/docs/machine-learning/coding/coding.html",{"title":"编程基础"},[":md"]],
  ["v-596f38ba","/docs/machine-learning/deep-learning/deep-learning.html",{"title":"深度学习"},[":md"]],
  ["v-88c89bcc","/docs/machine-learning/machine-learning-framework/machine-learning-framework.html",{"title":"机器学习框架"},[":md"]],
  ["v-69efe60c","/docs/machine-learning/mathematics/mathematics.html",{"title":"数学基础"},[":md"]],
  ["v-429a85ba","/docs/machine-learning/machine-learning/machine-learning.html",{"title":"机器学习"},[":md"]],
  ["v-ff0001cc","/docs/machine-learning/model-deployment/model-deployment.html",{"title":"模型部署"},[":md"]],
  ["v-1fe34b3a","/docs/machine-learning/multimodal-large-model/multimodal-large-model.html",{"title":"多模态机器学习"},[":md"]],
  ["v-5402b830","/docs/machine-learning/natural-language-processing/natural-language-processing.html",{"title":"自然语言处理"},[":md"]],
  ["v-5b3d7428","/docs/machine-learning/other/guide.html",{"title":"vuepress-theme-reco"},[":md"]],
  ["v-61990c1c","/docs/machine-learning/personal/list.html",{"title":"任务清单"},[":md"]],
  ["v-65554cb3","/docs/machine-learning/personal/material.html",{"title":"机器学习学习资料"},[":md"]],
  ["v-193fc2dd","/docs/machine-learning/personal/tools.html",{"title":"工具"},[":md"]],
  ["v-26a93578","/docs/machine-learning/perface/perface.html",{"title":"前言"},[":md"]],
  ["v-38244cb8","/docs/machine-learning/recommender-systems/recommender-systems.html",{"title":"推荐系统"},[":md"]],
  ["v-6c5ca2ba","/docs/machine-learning/reinforcement-learning/reinforcement-learning.html",{"title":"强化学习"},[":md"]],
  ["v-07b8fa3a","/blogs/photograph/Tokyo2023/K1/",{"title":"VOL.1 东京市区篇"},["/blogs/photograph/Tokyo2023/K1/README.md"]],
  ["v-07b8f9fc","/blogs/photograph/Tokyo2023/K2/",{"title":"VOL.2 湘南篇"},["/blogs/photograph/Tokyo2023/K2/README.md"]],
  ["v-75393e7e","/docs/machine-learning/artificial-general-intelligence/autopilot/autopilot.html",{"title":"自动驾驶"},[":md"]],
  ["v-6058a8f2","/docs/machine-learning/artificial-general-intelligence/industry-application/industry-application.html",{"title":"业界应用"},[":md"]],
  ["v-09ba5c07","/docs/machine-learning/auto-machine-learning/auto-machine-learning-introduction/auto-machine-learning-introduction.html",{"title":"AutoML介绍"},[":md"]],
  ["v-edf16eaa","/docs/machine-learning/auto-machine-learning/hyperparameter-optimization/hyperparameter-optimization.html",{"title":"超参数优化HPO"},[":md"]],
  ["v-51745d32","/docs/machine-learning/auto-machine-learning/neural-architecture-search/neural-architecture-search.html",{"title":"神经网络架构搜索NAS"},[":md"]],
  ["v-0e2e9e01","/docs/machine-learning/computer-vision/image-mark-tool/image-mark-tool.html",{"title":"图像标注工具"},[":md"]],
  ["v-6d639022","/docs/machine-learning/computer-vision/yolo/yolo.html",{"title":"前言"},[":md"]],
  ["v-5459fb3f","/docs/machine-learning/coding/big-data/big-data.html",{"title":"大数据"},[":md"]],
  ["v-4fba313f","/docs/machine-learning/coding/cs-courses/cs-courses.html",{"title":"计算机科学课程"},[":md"]],
  ["v-296f61cf","/docs/machine-learning/coding/programing-language/programing-language.html",{"title":"编程语言"},[":md"]],
  ["v-2cd08182","/docs/machine-learning/deep-learning/artificial-neural-network/artificial-neural-network.html",{"title":"ANN人工神经网络"},[":md"]],
  ["v-76a15832","/docs/machine-learning/deep-learning/beyesian-neural-network/beyesian-neural-network.html",{"title":"BNN贝叶斯神经网络"},[":md"]],
  ["v-15e071aa","/docs/machine-learning/deep-learning/convolutional-neural-network/convolutional-neural-network.html",{"title":"卷积神经网络"},[":md"]],
  ["v-a7093b2c","/docs/machine-learning/deep-learning/deep-generative-models/deep-generative-models.html",{"title":"深度生成模型介绍"},[":md"]],
  ["v-704e2f2a","/docs/machine-learning/deep-learning/deep-learning-introduction/deep-learning-introduction.html",{"title":"深度学习概论"},[":md"]],
  ["v-6773e6f0","/docs/machine-learning/deep-learning/few-shot-learning/few-shot-learning.html",{"title":"Few-shot Learning小样本学习"},[":md"]],
  ["v-c4df8000","/docs/machine-learning/deep-learning/graph-neural-networks/graph-neural-networks.html",{"title":"图神经网络"},[":md"]],
  ["v-224c1cb0","/docs/machine-learning/deep-learning/hopfield-neural-network/hopfield-neural-network.html",{"title":"Hopfield神经网络"},[":md"]],
  ["v-5203048a","/docs/machine-learning/deep-learning/recurrent-neural-network/recurrent-neural-network.html",{"title":"RNN循环神经网络"},[":md"]],
  ["v-aef1cc2c","/docs/machine-learning/deep-learning/tips/tips.html",{"title":"深度学习知识点"},[":md"]],
  ["v-1bf02674","/docs/machine-learning/machine-learning-framework/anaconda/anaconda.html",{"title":"Anaconda"},[":md"]],
  ["v-b7bd8d70","/docs/machine-learning/machine-learning-framework/cloud-server-platform/cloud-server-platform.html",{"title":"模型训练云服务器平台"},[":md"]],
  ["v-82d64d58","/docs/machine-learning/machine-learning-framework/large-model-trainning-method/large-model-trainning-method.html",{"title":"AI大模型训练框架"},[":md"]],
  ["v-4f5cb328","/docs/machine-learning/machine-learning-framework/pytorch/pytorch.html",{"title":"PyTorch"},[":md"]],
  ["v-4bde7504","/docs/machine-learning/machine-learning-framework/ray/ray.html",{"title":"Ray分布式计算框架"},[":md"]],
  ["v-e5454508","/docs/machine-learning/machine-learning-framework/rllib/rllib.html",{"title":"RLlib"},[":md"]],
  ["v-7715f658","/docs/machine-learning/machine-learning-framework/supercomputing-cluster/supercomputing-cluster.html",{"title":"超算集群"},[":md"]],
  ["v-70154bf4","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow.html",{"title":"TensorFlow"},[":md"]],
  ["v-6cc12453","/docs/machine-learning/mathematics/calculus/calculus.html",{"title":"微积分"},[":md"]],
  ["v-59328641","/docs/machine-learning/mathematics/gradient-update-algorithm/gradient-update-algorithm.html",{"title":"梯度更新算法"},[":md"]],
  ["v-0a0da4da","/docs/machine-learning/mathematics/information-theory/information-theory.html",{"title":"信息论"},[":md"]],
  ["v-1a89dd5a","/docs/machine-learning/mathematics/linear-algebra/linear-algebra.html",{"title":"线性代数"},[":md"]],
  ["v-737e5f33","/docs/machine-learning/mathematics/math-courses/math-courses.html",{"title":"数学专业课程"},[":md"]],
  ["v-78b128c7","/docs/machine-learning/mathematics/mathematics-map/mathematics-map.html",{"title":"数学系课程地图"},[":md"]],
  ["v-4fa4bb53","/docs/machine-learning/mathematics/mathematics-ml-needs/mathematics-ml-needs.html",{"title":"机器学习需要的数学"},[":md"]],
  ["v-4306d7d3","/docs/machine-learning/mathematics/numerical-calculation-and-optimization/numerical-calculation-and-optimization.html",{"title":"数值计算与优化"},[":md"]],
  ["v-8ce5da9a","/docs/machine-learning/mathematics/statistics/statistics.html",{"title":"概率统计"},[":md"]],
  ["v-4869d0a5","/docs/machine-learning/machine-learning/clustering/clustering.html",{"title":"聚类"},[":md"]],
  ["v-039da385","/docs/machine-learning/machine-learning/conditional-random-field/conditional-random-field.html",{"title":"CRF条件随机场"},[":md"]],
  ["v-febbfdf6","/docs/machine-learning/machine-learning/decision-tree/decision-tree.html",{"title":"决策树"},[":md"]],
  ["v-4c8833f6","/docs/machine-learning/machine-learning/dimensionality-reduction/dimensionality-reduction.html",{"title":"降维"},[":md"]],
  ["v-441718c2","/docs/machine-learning/machine-learning/ensemble-learning/ensemble-learning.html",{"title":"集成学习"},[":md"]],
  ["v-9a1f35f6","/docs/machine-learning/machine-learning/expectation-maximization-algorithm/expectation-maximization-algorithm.html",{"title":"EM算法"},[":md"]],
  ["v-08a9ecaa","/docs/machine-learning/machine-learning/feature-engineering/feature-engineering.html",{"title":"特征工程"},[":md"]],
  ["v-7b53c886","/docs/machine-learning/machine-learning/hidden-markov-model/hidden-markov-model.html",{"title":"HMM隐马尔科夫模型"},[":md"]],
  ["v-35327585","/docs/machine-learning/machine-learning/k-nearest-neighbor/k-nearest-neighbor.html",{"title":"k近邻法"},[":md"]],
  ["v-49e7358f","/docs/machine-learning/machine-learning/liblinear/liblinear.html",{"title":"LIBLINEAR"},[":md"]],
  ["v-2baca445","/docs/machine-learning/machine-learning/linear-model/linear-model.html",{"title":"线性模型"},[":md"]],
  ["v-152ed9f6","/docs/machine-learning/machine-learning/machine-learning-algorithm-summary/machine-learning-algorithm-summary.html",{"title":"机器学习算法总结"},[":md"]],
  ["v-d99027c6","/docs/machine-learning/machine-learning/machine-learning-introduction/machine-learning-introduction.html",{"title":"机器学习概论"},[":md"]],
  ["v-8b593cba","/docs/machine-learning/machine-learning/naive-bayes/naive-bayes.html",{"title":"朴素贝叶斯"},[":md"]],
  ["v-6a965f36","/docs/machine-learning/machine-learning/perceptron/perceptron.html",{"title":"感知机"},[":md"]],
  ["v-6809ddb5","/docs/machine-learning/machine-learning/probability-graphical-model/probability-graphical-model.html",{"title":"概率图模型"},[":md"]],
  ["v-999658f6","/docs/machine-learning/machine-learning/support-vector-machine/support-vector-machine.html",{"title":"支持向量机"},[":md"]],
  ["v-1598ede5","/docs/machine-learning/machine-learning/tips/tips.html",{"title":"知识点"},[":md"]],
  ["v-35e79f4d","/docs/machine-learning/machine-learning/topic-model/topic-model.html",{"title":"主题模型"},[":md"]],
  ["v-4df238f6","/docs/machine-learning/model-deployment/ai-compiler/ai-compiler.html",{"title":"AI编译器"},[":md"]],
  ["v-aab6c2bc","/docs/machine-learning/model-deployment/matrix-acceleration-algorithm/matrix-acceleration-algorithm.html",{"title":"矩阵加速算法"},[":md"]],
  ["v-59d7047a","/docs/machine-learning/model-deployment/model-compression/model-compression.html",{"title":"模型压缩"},[":md"]],
  ["v-87ee9cc0","/docs/machine-learning/model-deployment/model-deployment/model-deployment.html",{"title":"模型部署"},[":md"]],
  ["v-73a95440","/docs/machine-learning/model-deployment/parallel-computing/parallel-computing.html",{"title":"并行计算"},[":md"]],
  ["v-fc985fbe","/docs/machine-learning/multimodal-large-model/foundation-models/foundation-models.html",{"title":"Foundation Models基础模型"},[":md"]],
  ["v-6099240b","/docs/machine-learning/multimodal-large-model/industry-application/industry-application.html",{"title":"业界应用"},[":md"]],
  ["v-13620505","/docs/machine-learning/natural-language-processing/bert/bert.html",{"title":"BERT"},[":md"]],
  ["v-09e90d65","/docs/machine-learning/natural-language-processing/language-model-and-chinese-word-segmentation/language-model-and-chinese-word-segmentation.html",{"title":"语言模型和中文分词"},[":md"]],
  ["v-827a3336","/docs/machine-learning/natural-language-processing/large-language-model/large-language-model.html",{"title":"LLM大语言模型"},[":md"]],
  ["v-0654aa25","/docs/machine-learning/natural-language-processing/natural-language/natural-language.html",{"title":"自然语言"},[":md"]],
  ["v-68c67145","/docs/machine-learning/natural-language-processing/natural-language-processing-introduction/natural-language-processing-introduction.html",{"title":"自然语言处理概论"},[":md"]],
  ["v-394a3bc5","/docs/machine-learning/natural-language-processing/self-attention-and-transformer/self-attention-and-transformer.html",{"title":"Self-Attention机制和Transformer"},[":md"]],
  ["v-95e15a86","/docs/machine-learning/natural-language-processing/seq2seq-and-attention-mechanism/seq2seq-and-attention-mechanism.html",{"title":"Seq2Seq和注意力机制"},[":md"]],
  ["v-749d0065","/docs/machine-learning/natural-language-processing/tf-idf/tf-idf.html",{"title":"TF-IDF"},[":md"]],
  ["v-3d295725","/docs/machine-learning/natural-language-processing/word2vec/word2vec.html",{"title":"word2vec"},[":md"]],
  ["v-0cc54feb","/docs/machine-learning/perface/interview/interview.html",{"title":"机器学习面试"},[":md"]],
  ["v-cd3cb8e2","/docs/machine-learning/perface/machine-learning-history/machine-learning-history.html",{"title":"机器学习发展史"},[":md"]],
  ["v-683ff9e2","/docs/machine-learning/perface/machine-learning-learning-path/machine-learning-learning-path.html",{"title":"机器学习的学习路径"},[":md"]],
  ["v-18423ccf","/docs/machine-learning/perface/machine-learning-perface/machine-learning-perface.html",{"title":"机器学习前言"},[":md"]],
  ["v-2d8b9562","/docs/machine-learning/perface/personal-perface/personal-perface.html",{"title":"个人前言"},[":md"]],
  ["v-65d9fd89","/docs/machine-learning/recommender-systems/advanced-knowledge/advanced-knowledge.html",{"title":"进阶知识"},[":md"]],
  ["v-70c32049","/docs/machine-learning/recommender-systems/industry-application/industry-application.html",{"title":"业界应用"},[":md"]],
  ["v-172cb8ee","/docs/machine-learning/recommender-systems/recommender-systems-introduction/recommender-systems-introduction.html",{"title":"推荐系统概述"},[":md"]],
  ["v-22baa0b7","/docs/machine-learning/reinforcement-learning/decision-making-big-model/decision-making-big-model.html",{"title":"决策大模型"},[":md"]],
  ["v-2dba204f","/docs/machine-learning/reinforcement-learning/diffusion-model-rl/diffusion-model-rl.html",{"title":"DiffusionModel+RL"},[":md"]],
  ["v-79e16baf","/docs/machine-learning/reinforcement-learning/imatation-learning/imatation-learning.html",{"title":"模仿学习"},[":md"]],
  ["v-7527fd2f","/docs/machine-learning/reinforcement-learning/industry-application/industry-application.html",{"title":"业界应用"},[":md"]],
  ["v-73cf6762","/docs/machine-learning/reinforcement-learning/llm-rl/llm-rl.html",{"title":"LLM+RL"},[":md"]],
  ["v-4368736b","/docs/machine-learning/reinforcement-learning/monte-carlo-tree-search/monte-carlo-tree-search.html",{"title":"MCTS蒙特卡罗树搜索"},[":md"]],
  ["v-ec094762","/docs/machine-learning/reinforcement-learning/multi-agent-reinforcement-learning/multi-agent-reinforcement-learning.html",{"title":"多智能体强化学习"},[":md"]],
  ["v-2cb07b4f","/docs/machine-learning/reinforcement-learning/multi-modal-reinforcement-learning/multi-modal-reinforcement-learning.html",{"title":"MMRL多模态强化学习"},[":md"]],
  ["v-04d2de8f","/docs/machine-learning/reinforcement-learning/offline-reinforcement-learning/offline-reinforcement-learning.html",{"title":"离线强化学习"},[":md"]],
  ["v-29f9464f","/docs/machine-learning/reinforcement-learning/reinforcement-learning/reinforcement-learning.html",{"title":"强化学习"},[":md"]],
  ["v-1dbbc02f","/docs/machine-learning/reinforcement-learning/sim2real/sim2real.html",{"title":"Sim2Real"},[":md"]],
  ["v-5aa1bf4a","/docs/machine-learning/reinforcement-learning/simulation-platform/simulation-platform.html",{"title":"强化学习仿真环境"},[":md"]],
  ["v-e4526c62","/docs/machine-learning/reinforcement-learning/transformer-rl/transformer-rl.html",{"title":"Transformer+RL"},[":md"]],
  ["v-4af130fc","/docs/machine-learning/artificial-general-intelligence/autopilot/control/control.html",{"title":"控制"},[":md"]],
  ["v-3ae81c10","/docs/machine-learning/artificial-general-intelligence/autopilot/decision/decision.html",{"title":"决策"},[":md"]],
  ["v-4e20fa00","/docs/machine-learning/artificial-general-intelligence/autopilot/dynamic-model/dynamic-model.html",{"title":"规划"},[":md"]],
  ["v-a098a2dc","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/electromechanical-systems.html",{"title":"机电系统"},[":md"]],
  ["v-84b41310","/docs/machine-learning/artificial-general-intelligence/autopilot/guidance/guidance.html",{"title":"制导"},[":md"]],
  ["v-b6f0a290","/docs/machine-learning/artificial-general-intelligence/autopilot/navigation/navigation.html",{"title":"导航"},[":md"]],
  ["v-6a1bc4d8","/docs/machine-learning/artificial-general-intelligence/autopilot/planning/planning.html",{"title":"规划"},[":md"]],
  ["v-a8ab73a0","/docs/machine-learning/artificial-general-intelligence/industry-application/deepmind/deepmind.html",{"title":"DeepMind"},[":md"]],
  ["v-9704c560","/docs/machine-learning/artificial-general-intelligence/industry-application/google/google.html",{"title":"Google"},[":md"]],
  ["v-3d61fb70","/docs/machine-learning/artificial-general-intelligence/industry-application/openai/openai.html",{"title":"OpenAI"},[":md"]],
  ["v-48fa4bf7","/docs/machine-learning/auto-machine-learning/neural-architecture-search/weight-agnostic-nn/Weight-Agnostic-Neural-Networks.html",{"title":"权重无关的神经网络"},[":md"]],
  ["v-785ee67e","/docs/machine-learning/computer-vision/image-mark-tool/labelme/labelme.html",{"title":"Labelme打标工具"},[":md"]],
  ["v-ed4b0f58","/docs/machine-learning/computer-vision/image-mark-tool/yolo-mark/yolo-mark.html",{"title":"yolo_mark打标工具"},[":md"]],
  ["v-3853bf8b","/docs/machine-learning/computer-vision/yolo/darknet/darknet.html",{"title":"DarkNet深度学习框架"},[":md"]],
  ["v-7974d4ca","/docs/machine-learning/computer-vision/yolo/yolo-principle/yolo-principle.html",{"title":"YOLO原理"},[":md"]],
  ["v-77d6faca","/docs/machine-learning/computer-vision/yolo/yolov5/yolov5.html",{"title":"YOLOv5"},[":md"]],
  ["v-463bbead","/docs/machine-learning/coding/big-data/hadoop/hadoop.html",{"title":"Hadoop"},[":md"]],
  ["v-3d0c5acd","/docs/machine-learning/coding/big-data/hive/hive.html",{"title":"HIVE常用函数"},[":md"]],
  ["v-78372b82","/docs/machine-learning/coding/big-data/scala/scala.html",{"title":"Scala"},[":md"]],
  ["v-0dfae911","/docs/machine-learning/coding/big-data/spark/spark.html",{"title":"Spark"},[":md"]],
  ["v-2a2a22bd","/docs/machine-learning/coding/cs-courses/compiler-principles/compiler-principles.html",{"title":"编译原理"},[":md"]],
  ["v-37f9a6ee","/docs/machine-learning/coding/cs-courses/computer-network/computer-network.html",{"title":"计算机网络"},[":md"]],
  ["v-7b75343d","/docs/machine-learning/coding/cs-courses/computer-organization/computer-organization.html",{"title":"编译原理"},[":md"]],
  ["v-628822af","/docs/machine-learning/coding/cs-courses/cs-courses-introduction/cs-courses-introduction.html",{"title":"计算机专业课程概述"},[":md"]],
  ["v-67976e49","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/data-structures-and-algorithms.html",{"title":"数据结构与算法"},[":md"]],
  ["v-3a7ae2a9","/docs/machine-learning/coding/cs-courses/operating-system/operating-system.html",{"title":"操作系统"},[":md"]],
  ["v-3bc0fc82","/docs/machine-learning/coding/programing-language/c__/c__.html",{"title":"c++"},["/docs/machine-learning/coding/programing-language/c++/c++.html","/docs/machine-learning/coding/programing-language/c++/c++.md"]],
  ["v-6b5d26f2","/docs/machine-learning/coding/programing-language/python/python.html",{"title":"python"},[":md"]],
  ["v-2a29da86","/docs/machine-learning/deep-learning/beyesian-neural-network/beyesian-neural-network/beyesian-neural-network.html",{"title":"贝叶斯神经网络"},[":md"]],
  ["v-30ba2cbe","/docs/machine-learning/deep-learning/beyesian-neural-network/weight-uncertainty-in-neural-networks/Weight-Uncertainty-in-Neural-Networks.html",{"title":"Weight Uncertainty in Neural Networks"},[":md"]],
  ["v-ffa547a2","/docs/machine-learning/deep-learning/convolutional-neural-network/convolutional-neural-network/convolutional-neural-network.html",{"title":"CNN卷积神经网络"},[":md"]],
  ["v-67c576ef","/docs/machine-learning/deep-learning/convolutional-neural-network/textcnn/Convolutional-Neural-Networks-for-Sentence-Classification.html",{"title":"TextCNN"},[":md"]],
  ["v-c560e9d2","/docs/machine-learning/deep-learning/deep-generative-models/deep-generative-models-introduction/deep-generative-models-introduction.html",{"title":"深度生成模型介绍"},[":md"]],
  ["v-41d0d04b","/docs/machine-learning/deep-learning/deep-generative-models/diffusion-models/diffusion-models.html",{"title":"扩散模型"},[":md"]],
  ["v-db1a9dce","/docs/machine-learning/deep-learning/deep-generative-models/generative-adversarial-nets/generative-adversarial-nets.html",{"title":"GAN生成对抗网络"},[":md"]],
  ["v-42ac8166","/docs/machine-learning/deep-learning/deep-generative-models/variational-autoencoder/variational-autoencoder.html",{"title":"变分自编码器"},[":md"]],
  ["v-9be41c7a","/docs/machine-learning/deep-learning/graph-neural-networks/graph-attention-network/graph-attention-network.html",{"title":"GCN图卷积网络"},[":md"]],
  ["v-517c56c5","/docs/machine-learning/deep-learning/graph-neural-networks/graph-convolutional-networks/graph-convolutional-networks.html",{"title":"GCN图卷积网络"},[":md"]],
  ["v-25f897e5","/docs/machine-learning/deep-learning/graph-neural-networks/graph-neural-networks-review/graph-neural-networks-review.html",{"title":"图神经网络综述"},[":md"]],
  ["v-3d15f4f2","/docs/machine-learning/deep-learning/recurrent-neural-network/gated-recurrent-unit/gated-recurrent-unit.html",{"title":"GRU门控循环单元"},[":md"]],
  ["v-43df57ac","/docs/machine-learning/deep-learning/recurrent-neural-network/long-short-term-memory-networks/long-short-term-memory-networks.html",{"title":"LSTM长短期记忆网络"},[":md"]],
  ["v-99eb881c","/docs/machine-learning/deep-learning/recurrent-neural-network/recurrent-neural-network/recurrent-neural-network.html",{"title":"RNN循环神经网络"},[":md"]],
  ["v-059e0561","/docs/machine-learning/deep-learning/tips/activation-functions/activation-functions.html",{"title":"激活函数"},[":md"]],
  ["v-52428b7e","/docs/machine-learning/deep-learning/tips/feature-crossing/feature-crossing.html",{"title":"深度学习的高阶特征交叉原理"},[":md"]],
  ["v-2e44143e","/docs/machine-learning/deep-learning/tips/gradient-explosion-and-vanishing/gradient-explosion-and-vanishing.html",{"title":"梯度爆炸和梯度消失"},[":md"]],
  ["v-3d882fa5","/docs/machine-learning/deep-learning/tips/normalization/normalization.html",{"title":"深度学习中的正则化"},[":md"]],
  ["v-06782012","/docs/machine-learning/machine-learning-framework/pytorch/basis/basis.html",{"title":"Pytorch基础"},[":md"]],
  ["v-4e182709","/docs/machine-learning/machine-learning-framework/supercomputing-cluster/microsoft-supercomputing-cluster-for-chatgpt/microsoft-supercomputing-cluster-for-chatgpt.html",{"title":"微软: 用于训练ChatGPT的超算"},[":md"]],
  ["v-323bfb80","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow-distributed-architecture/tensorflow-distributed-architecture.html",{"title":"Tensorflow分布式架构"},[":md"]],
  ["v-6fd8a52e","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow1.0/tensorflow1.0.html",{"title":"TensorFlow1.0"},[":md"]],
  ["v-5e3f8cac","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow2.0/tensorflow2.0.html",{"title":"TensorFlow2.0"},[":md"]],
  ["v-1207e928","/docs/machine-learning/machine-learning-framework/tensorflow/tf_serving/tf_serving.html",{"title":"TensorFlow Serving"},[":md"]],
  ["v-44612de0","/docs/machine-learning/machine-learning-framework/tensorflow/tools/tools.html",{"title":"工具"},[":md"]],
  ["v-40b0a4d4","/docs/machine-learning/mathematics/calculus/convolution/convolution.html",{"title":"卷积"},[":md"]],
  ["v-49033da6","/docs/machine-learning/mathematics/calculus/fourier-transform/fourier-transform.html",{"title":"傅里叶变换"},[":md"]],
  ["v-bf8e0c9c","/docs/machine-learning/mathematics/calculus/hilbert-space/hilbert-space.html",{"title":"希尔伯特空间"},[":md"]],
  ["v-ae275e34","/docs/machine-learning/mathematics/calculus/intuition-of-e/intuition-of-e.html",{"title":"e的直观认识"},[":md"]],
  ["v-4b72c766","/docs/machine-learning/mathematics/calculus/taylor-expansion/taylor-expansion.html",{"title":"泰勒展开"},[":md"]],
  ["v-4a1100ba","/docs/machine-learning/mathematics/gradient-update-algorithm/incremental-learning/incremental-learning.html",{"title":"增量学习"},[":md"]],
  ["v-eb73264c","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/offline-learning.html",{"title":"梯度下降算法"},[":md"]],
  ["v-70f5dca8","/docs/machine-learning/mathematics/gradient-update-algorithm/online-learning/online-learning.html",{"title":"在线学习"},[":md"]],
  ["v-1edc7566","/docs/machine-learning/mathematics/information-theory/information-theory-introduction/information-theory-introduction.html",{"title":"信息论基础"},[":md"]],
  ["v-e553b0a0","/docs/machine-learning/mathematics/linear-algebra/eigenvalue/eigenvalue.html",{"title":"特征值"},[":md"]],
  ["v-216b2b68","/docs/machine-learning/mathematics/linear-algebra/matrix-derivative/matrix-derivative.html",{"title":"矩阵求导"},[":md"]],
  ["v-17231ad0","/docs/machine-learning/mathematics/linear-algebra/norm/norm.html",{"title":"范数"},[":md"]],
  ["v-9c2d6420","/docs/machine-learning/mathematics/linear-algebra/singular-value-decomposition/singular-value-decomposition.html",{"title":"SVD奇异值分解"},[":md"]],
  ["v-53fa132f","/docs/machine-learning/mathematics/math-courses/functional-analysis/functional-analysis.html",{"title":""},[":md"]],
  ["v-27008f7d","/docs/machine-learning/mathematics/math-courses/linear-algebra/linear-algebra.html",{"title":"线性代数"},[":md"]],
  ["v-15a93f46","/docs/machine-learning/mathematics/math-courses/math-principle/math-principle.html",{"title":"数学的原理"},[":md"]],
  ["v-342f7a61","/docs/machine-learning/mathematics/math-courses/variational-principle/variational-principle.html",{"title":"变分原理"},[":md"]],
  ["v-32560ce8","/docs/machine-learning/mathematics/numerical-calculation-and-optimization/convex-optimization/convex-optimization.html",{"title":"凸优化"},[":md"]],
  ["v-476db5f4","/docs/machine-learning/mathematics/numerical-calculation-and-optimization/lagrangian-multiplier-method/lagrangian-multiplier-method.html",{"title":"等式约束的拉格朗日乘子法"},[":md"]],
  ["v-f9777c50","/docs/machine-learning/mathematics/numerical-calculation-and-optimization/least-square-method/least-square-method.html",{"title":"最小二乘法"},[":md"]],
  ["v-01f78655","/docs/machine-learning/mathematics/statistics/bayesian-analysis/bayesian-analysis.html",{"title":"贝叶斯分析方法"},[":md"]],
  ["v-a19ec066","/docs/machine-learning/mathematics/statistics/probability-distribution/probability-distribution.html",{"title":"概率分布"},[":md"]],
  ["v-7a2a0583","/docs/machine-learning/mathematics/statistics/statistics-introduction/statistics-introduction.html",{"title":"概率统计基础"},[":md"]],
  ["v-5ab80326","/docs/machine-learning/mathematics/statistics/variance-and-covariance/variance-and-covariance.html",{"title":"方差与协方差"},[":md"]],
  ["v-66888540","/docs/machine-learning/machine-learning/clustering/dbscan-clustering/dbscan-clustering.html",{"title":"DBSCAN聚类"},[":md"]],
  ["v-baa529c4","/docs/machine-learning/machine-learning/clustering/dirichlet-process-mixture-model/dirichlet-process-mixture-model.html",{"title":"DPMM狄利克雷过程混合模型"},[":md"]],
  ["v-47477996","/docs/machine-learning/machine-learning/clustering/gaussian-mixture-model/gaussian-mixture-model.html",{"title":"高斯混合模型"},[":md"]],
  ["v-b1fa1688","/docs/machine-learning/machine-learning/clustering/hierarchical-clustering/hierarchical-clustering.html",{"title":"层次聚类"},[":md"]],
  ["v-37ff1776","/docs/machine-learning/machine-learning/clustering/k-means-clustering/k-means-clustering.html",{"title":"k均值聚类"},[":md"]],
  ["v-17c9c31c","/docs/machine-learning/machine-learning/clustering/spectral-clustering/spectral-clustering.html",{"title":"谱聚类"},[":md"]],
  ["v-455f82f1","/docs/machine-learning/machine-learning/dimensionality-reduction/dimensionality-reduction-introduction/dimensionality-reduction-introduction.html",{"title":"降维概述"},[":md"]],
  ["v-5168f903","/docs/machine-learning/machine-learning/dimensionality-reduction/manifold-learning/manifold-learning.html",{"title":"流形学习"},[":md"]],
  ["v-1fc4959b","/docs/machine-learning/machine-learning/dimensionality-reduction/principal-component-analysis/principal-component-analysis.html",{"title":"PCA主成分分析"},[":md"]],
  ["v-c9cfb82c","/docs/machine-learning/machine-learning/ensemble-learning/bagging/bagging.html",{"title":"Bagging"},[":md"]],
  ["v-5536a312","/docs/machine-learning/machine-learning/ensemble-learning/boosting/boosting.html",{"title":"Boosting"},[":md"]],
  ["v-aa7d085c","/docs/machine-learning/machine-learning/ensemble-learning/ensemble-learning-introduction/ensemble-learning-introduction.html",{"title":"集成学习概述"},[":md"]],
  ["v-721ef4b2","/docs/machine-learning/machine-learning/ensemble-learning/stacking/stacking.html",{"title":"Stacking"},[":md"]],
  ["v-4b1f41dd","/docs/machine-learning/machine-learning/linear-model/exponential-family-distribution-and-generalized-linear-model/exponential-family-distribution-and-generalized-linear-model.html",{"title":"指数族分布与广义线性模型"},[":md"]],
  ["v-1a7bbf89","/docs/machine-learning/machine-learning/linear-model/linear-regression/linear-regression.html",{"title":"线性回归"},[":md"]],
  ["v-660b0b7f","/docs/machine-learning/machine-learning/linear-model/logistic-regression/logistic-regression.html",{"title":"Logistic回归"},[":md"]],
  ["v-53b27d9b","/docs/machine-learning/machine-learning/linear-model/maximum-entropy-model/maximum-entropy-model.html",{"title":"最大熵模型"},[":md"]],
  ["v-463e33f1","/docs/machine-learning/machine-learning/machine-learning-introduction/model-composition-and-classification/model-composition-and-classification.html",{"title":"机器学习模型组成与分类"},[":md"]],
  ["v-c7dbb89e","/docs/machine-learning/machine-learning/machine-learning-introduction/model-evaluation-and-performance/model-evaluation-and-performance.html",{"title":"模型评估方法与性能度量"},[":md"]],
  ["v-910d315e","/docs/machine-learning/machine-learning/machine-learning-introduction/over-fitting-and-model-complexity/over-fitting-and-model-complexity.html",{"title":"过拟合与模型复杂度"},[":md"]],
  ["v-32ead99e","/docs/machine-learning/machine-learning/machine-learning-introduction/philosophy/philosophy.html",{"title":"机器学习的哲学思想"},[":md"]],
  ["v-2e7bcfde","/docs/machine-learning/machine-learning/machine-learning-introduction/regularization/regularization.html",{"title":"正则化"},[":md"]],
  ["v-1a0fd27d","/docs/machine-learning/machine-learning/probability-graphical-model/probability-graph-introduction/probability-graph-introduction.html",{"title":"概率图简介"},[":md"]],
  ["v-b0a23cc6","/docs/machine-learning/machine-learning/probability-graphical-model/probability-graphical-model-introduction/probability-graphical-model-introduction.html",{"title":"概率图模型简介"},[":md"]],
  ["v-20115023","/docs/machine-learning/machine-learning/support-vector-machine/linear-separable-svm/linear-separable-svm.html",{"title":"线性可分支持向量机与硬间隔最大化"},[":md"]],
  ["v-2c90d83a","/docs/machine-learning/machine-learning/support-vector-machine/linear-svm/linear-svm.html",{"title":"线性支持向量机与软间隔最大化"},[":md"]],
  ["v-b139680e","/docs/machine-learning/machine-learning/support-vector-machine/nonlinear-svm-and-kernel-function/nonlinear-svm-and-kernel-function.html",{"title":"非线性支持向量机与核函数"},[":md"]],
  ["v-dff71492","/docs/machine-learning/machine-learning/support-vector-machine/smo/smo.html",{"title":"序列最小最优化算法SMO"},[":md"]],
  ["v-1d51374a","/docs/machine-learning/machine-learning/support-vector-machine/svm-summary/svm-summary.html",{"title":"SVM总结"},[":md"]],
  ["v-59fe4e00","/docs/machine-learning/machine-learning/tips/loss-function/loss-function.html",{"title":"损失函数"},[":md"]],
  ["v-7fe68d74","/docs/machine-learning/machine-learning/tips/negtive-sampling/negtive-sampling.html",{"title":"负采样"},[":md"]],
  ["v-b954c882","/docs/machine-learning/machine-learning/topic-model/latent-dirichlet-allocation/latent-dirichlet-allocation.html",{"title":"LDA隐狄利克雷分布"},[":md"]],
  ["v-60df1381","/docs/machine-learning/model-deployment/matrix-acceleration-algorithm/im2col/im2col.html",{"title":"im2col: 将卷积转为矩阵乘法来加速计算"},[":md"]],
  ["v-952d81fa","/docs/machine-learning/model-deployment/matrix-acceleration-algorithm/winograd/Fast-Algorithms-for-Convolutional-Neural-Networks.html",{"title":"Fast Algorithms for Convolutional Neural Networks"},[":md"]],
  ["v-49285de6","/docs/machine-learning/model-deployment/model-compression/knowledge-distillation/knowledge-distillation.html",{"title":"知识蒸馏"},[":md"]],
  ["v-54c3818d","/docs/machine-learning/model-deployment/model-compression/model-compression-introduction/model-compression-introduction.html",{"title":"模型压缩概述"},[":md"]],
  ["v-0f9041e6","/docs/machine-learning/model-deployment/model-compression/quantization/quantization.html",{"title":"量化quantization"},[":md"]],
  ["v-2c33784c","/docs/machine-learning/model-deployment/model-deployment/tensor-rt/tensor-rt.html",{"title":"TensorRT"},[":md"]],
  ["v-6faea0ce","/docs/machine-learning/model-deployment/model-deployment/tensorflow-cpp-deployment/tensorflow-cpp-deployment.html",{"title":"基于C/C++部署TensorFlow模型"},[":md"]],
  ["v-6edc92f5","/docs/machine-learning/model-deployment/parallel-computing/cuda/cuda.html",{"title":"CUDA"},[":md"]],
  ["v-debd5bd6","/docs/machine-learning/model-deployment/parallel-computing/openblas/openblas.html",{"title":"OpenBlas"},[":md"]],
  ["v-6df551f5","/docs/machine-learning/model-deployment/parallel-computing/opencl/opencl.html",{"title":"OpenCL"},[":md"]],
  ["v-127cff35","/docs/machine-learning/model-deployment/parallel-computing/openmp/openmp.html",{"title":"OpenMP"},[":md"]],
  ["v-55bc7488","/docs/machine-learning/multimodal-large-model/foundation-models/Can-Foundation-Models-Perform-Zero-Shot-For-Robot/Can-Foundation-Models-Perform-Zero-Shot-For-Robot.html",{"title":"Can Foundation Models Perform Zero-Shot Task Specification For Robot Manipulation?"},[":md"]],
  ["v-f528320c","/docs/machine-learning/multimodal-large-model/foundation-models/foundation-models-LeiFeiFei/On-the-Opportunities-and-Risks-of-Foundation-Models.html",{"title":"On the Opportunities and Risks of Foundation Models"},[":md"]],
  ["v-8ebe4b12","/docs/machine-learning/multimodal-large-model/industry-application/openai/openai.html",{"title":"OpenAI"},[":md"]],
  ["v-a6d02a08","/docs/machine-learning/natural-language-processing/large-language-model/emergence/emergence.html",{"title":"Emergence涌现现象"},[":md"]],
  ["v-a0b6fdd0","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/industry-application.html",{"title":"业界应用"},[":md"]],
  ["v-29d17928","/docs/machine-learning/natural-language-processing/large-language-model/prompt-learning/prompt-learning.html",{"title":"Prompt Learning"},[":md"]],
  ["v-f932aa90","/docs/machine-learning/natural-language-processing/large-language-model/rlhf/rlhf.html",{"title":"RLHF基于人工反馈的强化学习方法"},[":md"]],
  ["v-2c68d10c","/docs/machine-learning/natural-language-processing/large-language-model/train-ChatGPT-DIY/train-ChatGPT-DIY.html",{"title":"自己训练ChatGPT"},[":md"]],
  ["v-7532c661","/docs/machine-learning/natural-language-processing/self-attention-and-transformer/attention-is-all-you-need/attention-is-all-you-need.html",{"title":"Attention Is All You Need"},[":md"]],
  ["v-60a17de6","/docs/machine-learning/natural-language-processing/self-attention-and-transformer/transformer-details/transformer-details.html",{"title":"transformer的细节问题"},[":md"]],
  ["v-24a070e9","/docs/machine-learning/natural-language-processing/self-attention-and-transformer/transformer-tf2-demo-code-explain/transformer-tf2-demo-code-explain.html",{"title":"Transformer模型TF2官网demo代码解读"},[":md"]],
  ["v-cb60ed1c","/docs/machine-learning/natural-language-processing/word2vec/word2vec-algorithm-principle/word2vec-algorithm-principle.html",{"title":"word2vec算法原理"},[":md"]],
  ["v-5825e21a","/docs/machine-learning/natural-language-processing/word2vec/word2vec-introduction/word2vec-introduction.html",{"title":"word2vector概述"},[":md"]],
  ["v-5d17b858","/docs/machine-learning/natural-language-processing/word2vec/word2vec-practice/word2vec-practice.html",{"title":"word2vector实践"},[":md"]],
  ["v-a653018c","/docs/machine-learning/natural-language-processing/word2vec/word2vec-source-code-analysis/word2vec-source-code-analysis.html",{"title":"word2vec源码解析"},[":md"]],
  ["v-10a196f2","/docs/machine-learning/recommender-systems/advanced-knowledge/deep-learning/deep-learning.html",{"title":"Deep Learning"},[":md"]],
  ["v-72df5b7b","/docs/machine-learning/recommender-systems/advanced-knowledge/graph-convolutional-network/graph-convolutional-network.html",{"title":"图卷积网络"},[":md"]],
  ["v-6cb6e456","/docs/machine-learning/recommender-systems/advanced-knowledge/graph-embedding/graph-embedding.html",{"title":"图表征"},[":md"]],
  ["v-a9479b12","/docs/machine-learning/recommender-systems/advanced-knowledge/interpretable/interpretable.html",{"title":"可解释性"},[":md"]],
  ["v-02ba5147","/docs/machine-learning/recommender-systems/advanced-knowledge/knowledge-graph/knowledge-graph.html",{"title":"知识图谱"},[":md"]],
  ["v-0e0fb3c7","/docs/machine-learning/recommender-systems/advanced-knowledge/machine-learning/machine-learning.html",{"title":"机器学习"},[":md"]],
  ["v-5381d77e","/docs/machine-learning/recommender-systems/advanced-knowledge/multy-task-learning/multy-task-learning.html",{"title":"多任务学习"},[":md"]],
  ["v-fc241272","/docs/machine-learning/recommender-systems/advanced-knowledge/rank-model-introduction/rank-model-introduction.html",{"title":"排序模型概述"},[":md"]],
  ["v-5da6dfd1","/docs/machine-learning/recommender-systems/advanced-knowledge/recall-model-introduction/recall-model-introduction.html",{"title":"召回模型概述"},[":md"]],
  ["v-58242547","/docs/machine-learning/recommender-systems/advanced-knowledge/reinforcement-learning/reinforcement-learning.html",{"title":"reinforcement-learning"},[":md"]],
  ["v-0ac8417f","/docs/machine-learning/recommender-systems/industry-application/alibaba/alibaba.html",{"title":"Alibaba"},[":md"]],
  ["v-5fb68d39","/docs/machine-learning/recommender-systems/industry-application/facebook/facebook.html",{"title":"Facebook"},[":md"]],
  ["v-76e2ac4e","/docs/machine-learning/recommender-systems/industry-application/google/google.html",{"title":"Google"},[":md"]],
  ["v-e1896956","/docs/machine-learning/recommender-systems/industry-application/youtube/Top-K-Off-Policy-Correction-for-a-REINFORCE-Recommender-System.html",{"title":"YouTube深度学习推荐系统"},[":md"]],
  ["v-698be164","/docs/machine-learning/recommender-systems/industry-application/youtube/Youtube%E6%8F%90%E5%87%BA%E5%8F%8C%E5%A1%94%E7%BB%93%E6%9E%84%E6%B5%81%E5%BC%8F%E6%A8%A1%E5%9E%8B%E8%BF%9B%E8%A1%8C%E5%A4%A7%E8%A7%84%E6%A8%A1%E6%8E%A8%E8%8D%90.html",{"title":"YouTube深度学习推荐系统"},["/docs/machine-learning/recommender-systems/industry-application/youtube/Youtube提出双塔结构流式模型进行大规模推荐.html","/docs/machine-learning/recommender-systems/industry-application/youtube/Youtube提出双塔结构流式模型进行大规模推荐.md",":md"]],
  ["v-9ecc6c9e","/docs/machine-learning/recommender-systems/industry-application/youtube/youtube.html",{"title":"YouTube"},[":md"]],
  ["v-7958e207","/docs/machine-learning/reinforcement-learning/imatation-learning/behavior-cloning/behavior-cloning.html",{"title":"行为克隆"},[":md"]],
  ["v-2c7f98d7","/docs/machine-learning/reinforcement-learning/imatation-learning/generative-adversarial-imitation-learning/Generative-Adversarial-Imitation-Learning.html",{"title":"GAIL：生成对抗式模仿学习"},[":md"]],
  ["v-1ce4a91e","/docs/machine-learning/reinforcement-learning/imatation-learning/imatation-learning-introduction/imatation-learning-introduction.html",{"title":"模仿学习介绍"},[":md"]],
  ["v-3a0edb87","/docs/machine-learning/reinforcement-learning/imatation-learning/inverse-reinforcement-learning/inverse-reinforcement-learning.html",{"title":"IRL逆强化学习: Inverse Reinforcement Learning"},[":md"]],
  ["v-660f1266","/docs/machine-learning/reinforcement-learning/imatation-learning/paper/paper.html",{"title":"模仿学习论文"},[":md"]],
  ["v-8e56b9da","/docs/machine-learning/reinforcement-learning/industry-application/deepmind/deepmind.html",{"title":"DeepMind"},[":md"]],
  ["v-429884bd","/docs/machine-learning/reinforcement-learning/industry-application/inspir-ai/inspir-ai.html",{"title":"InspirAI启元世界"},[":md"]],
  ["v-c0a77c5a","/docs/machine-learning/reinforcement-learning/industry-application/openai/openai.html",{"title":"OpenAI"},[":md"]],
  ["v-00dbf147","/docs/machine-learning/reinforcement-learning/industry-application/tencent/tencent.html",{"title":"腾讯"},[":md"]],
  ["v-34cd4574","/docs/machine-learning/reinforcement-learning/multi-agent-reinforcement-learning/mappo/mappo.html",{"title":"多智能体强化学习论文"},[":md"]],
  ["v-044e1e38","/docs/machine-learning/reinforcement-learning/multi-agent-reinforcement-learning/paper/paper.html",{"title":"多智能体强化学习论文"},[":md"]],
  ["v-3982413c","/docs/machine-learning/reinforcement-learning/reinforcement-learning/deep-reinforcement-learning/deep-reinforcement-learning.html",{"title":"深度强化学习"},[":md"]],
  ["v-d3ff817c","/docs/machine-learning/reinforcement-learning/reinforcement-learning/dynamic-programming/dynamic-programming.html",{"title":"动态规划"},[":md"]],
  ["v-47d3023c","/docs/machine-learning/reinforcement-learning/reinforcement-learning/function-approximation-and-deep-network/function-approximation-and-deep-network.html",{"title":"函数近似和深度网络"},[":md"]],
  ["v-02612a8e","/docs/machine-learning/reinforcement-learning/reinforcement-learning/markov-decision-processes/markov-decision-processes.html",{"title":"马尔科夫决策过程"},[":md"]],
  ["v-1010bb5a","/docs/machine-learning/reinforcement-learning/reinforcement-learning/model-based-reinforcement-learning/model-based-reinforcement-learning.html",{"title":"基于模型的强化学习"},[":md"]],
  ["v-3a88438c","/docs/machine-learning/reinforcement-learning/reinforcement-learning/model-free-methods-1-monte-carlo/model-free-methods-1-monte-carlo.html",{"title":"无模型方法一：蒙特卡洛"},[":md"]],
  ["v-6d3abc4c","/docs/machine-learning/reinforcement-learning/reinforcement-learning/model-free-methods-2-time-difference/model-free-methods-2-time-difference.html",{"title":"无模型方法二：时间差分"},[":md"]],
  ["v-244a001c","/docs/machine-learning/reinforcement-learning/reinforcement-learning/model-free-methods-3-multi-step-bootstrap/model-free-methods-3-multi-step-bootstrap.html",{"title":"无模型方法三：多步自举"},[":md"]],
  ["v-fee6560c","/docs/machine-learning/reinforcement-learning/reinforcement-learning/multi-armed-bandit-and-solutions/multi-armed-bandit-and-solutions.html",{"title":"多臂赌博机及其解法"},[":md"]],
  ["v-9d399c80","/docs/machine-learning/reinforcement-learning/reinforcement-learning/paper/paper.html",{"title":"强化学习论文"},[":md"]],
  ["v-5c1ad8be","/docs/machine-learning/reinforcement-learning/reinforcement-learning/policy-gradient-algorithm/policy-gradient-algorithm.html",{"title":"策略梯度算法"},[":md"]],
  ["v-54ad6c58","/docs/machine-learning/reinforcement-learning/reinforcement-learning/reinforcement-learning-code/reinforcement-learning-code.html",{"title":"强化学习代码实现"},[":md"]],
  ["v-a5432c84","/docs/machine-learning/reinforcement-learning/reinforcement-learning/reinforcement-learning-introduction/reinforcement-learning-introduction.html",{"title":"强化学习概论"},[":md"]],
  ["v-55f94b5a","/docs/machine-learning/reinforcement-learning/reinforcement-learning/reinforcement-learning-prospect/reinforcement-learning-prospect.html",{"title":"强化学习前景"},[":md"]],
  ["v-2f21c830","/docs/machine-learning/reinforcement-learning/reinforcement-learning/state-reward-action/state-reward-action.html",{"title":"状态、奖励、动作"},[":md"]],
  ["v-7d7cd6c1","/docs/machine-learning/reinforcement-learning/sim2real/paper/paper.html",{"title":"模仿学习论文"},[":md"]],
  ["v-00c92a45","/docs/machine-learning/reinforcement-learning/simulation-platform/OpenDILab-GoBigger/OpenDILab-GoBigger.html",{"title":"OpenDILab的GoBigger"},[":md"]],
  ["v-a8c0b136","/docs/machine-learning/reinforcement-learning/simulation-platform/openai-gym/openai-gym.html",{"title":"OpenAI的Gym"},[":md"]],
  ["v-00bec8e2","/docs/machine-learning/artificial-general-intelligence/autopilot/control/llm-based-control/llm-based-control.html",{"title":"基于LLM大语言模型的控制"},[":md"]],
  ["v-75478b1c","/docs/machine-learning/artificial-general-intelligence/autopilot/control/pid-control/pid-control.html",{"title":"PID控制"},[":md"]],
  ["v-745e56ea","/docs/machine-learning/artificial-general-intelligence/autopilot/control/reinforcement-learning-based-control/reinforcement-learning-based-control.html",{"title":"基于强化学习的控制"},[":md"]],
  ["v-1caa5ccc","/docs/machine-learning/artificial-general-intelligence/autopilot/dynamic-model/aerodynamics/aerodynamics.html",{"title":"空气动力学"},[":md"]],
  ["v-f5df4a16","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/dynamic-system/dynamic-system.html",{"title":"动力系统"},[":md"]],
  ["v-60d859be","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/sensors.html",{"title":"各类型传感器"},[":md"]],
  ["v-eb2916e6","/docs/machine-learning/artificial-general-intelligence/autopilot/navigation/coord-trans-and-euler-kinematics-equation/coord-trans-and-euler-kinematics-equation.html",{"title":"坐标变换与欧拉运动学方程"},[":md"]],
  ["v-70cbe3d2","/docs/machine-learning/artificial-general-intelligence/autopilot/navigation/coriolis-theorem/coriolis-theorem.html",{"title":"哥氏定理/科里奥利定理"},[":md"]],
  ["v-1cad58aa","/docs/machine-learning/artificial-general-intelligence/autopilot/navigation/navigation-coord-system-and-trans/navigation-coord-system-and-trans.html",{"title":"导航常用坐标系及变换"},[":md"]],
  ["v-11566237","/docs/machine-learning/artificial-general-intelligence/autopilot/navigation/quaternion/quaternion.html",{"title":"四元数"},[":md"]],
  ["v-ac3e8524","/docs/machine-learning/artificial-general-intelligence/autopilot/planning/llm-based-planning/llm-based-planning.html",{"title":"基于LLM大语言模型的规划"},[":md"]],
  ["v-0ea135c1","/docs/machine-learning/artificial-general-intelligence/industry-application/deepmind/deepmind-introduction/deepmind-introduction.html",{"title":"DeepMind介绍"},[":md"]],
  ["v-4364e2c4","/docs/machine-learning/artificial-general-intelligence/industry-application/deepmind/gato/A-Generalist-Agent.html",{"title":"Gato: A Generalist Agent"},[":md"]],
  ["v-ab5b40f8","/docs/machine-learning/artificial-general-intelligence/industry-application/deepmind/pathnet/PathNet%EF%BC%9AEvolution-Channels-Gradient-Descent-in-Super-Neural-Networks.html",{"title":"PathNet"},["/docs/machine-learning/artificial-general-intelligence/industry-application/deepmind/pathnet/PathNet：Evolution-Channels-Gradient-Descent-in-Super-Neural-Networks.html","/docs/machine-learning/artificial-general-intelligence/industry-application/deepmind/pathnet/PathNet：Evolution-Channels-Gradient-Descent-in-Super-Neural-Networks.md",":md"]],
  ["v-15efb315","/docs/machine-learning/artificial-general-intelligence/industry-application/deepmind/reward-is-enough/Reward-is-enough.html",{"title":"Reward is enough"},[":md"]],
  ["v-6140929e","/docs/machine-learning/artificial-general-intelligence/industry-application/openai/emergence_lauguage_in_ma/Emergence-of-Grounded-Compositional-Language-in-Multi-Agent-Populations.html",{"title":"Emergence of Grounded Compositional Language in Multi-Agent Populations"},[":md"]],
  ["v-66571075","/docs/machine-learning/artificial-general-intelligence/industry-application/openai/openai-introduction/openai-introduction.html",{"title":"OpenAI介绍"},[":md"]],
  ["v-5b18bf91","/docs/machine-learning/coding/big-data/hadoop/commands/commands.html",{"title":"Hadoop常用命令"},[":md"]],
  ["v-1993b36a","/docs/machine-learning/coding/big-data/hadoop/hadoop-introduction/hadoop-introduction.html",{"title":"Hadoop简介"},[":md"]],
  ["v-4dc78931","/docs/machine-learning/coding/big-data/hadoop/map-reduce/map-reduce.html",{"title":"MapReduce"},[":md"]],
  ["v-fecebfac","/docs/machine-learning/coding/big-data/scala/advanced-type/advanced-type.html",{"title":"高级类型"},[":md"]],
  ["v-49973136","/docs/machine-learning/coding/big-data/scala/data-structure/data-structure.html",{"title":"数据结构"},[":md"]],
  ["v-aa10f6a8","/docs/machine-learning/coding/big-data/scala/pattern-matching-and-case-class/pattern-matching-and-case-class.html",{"title":"模式匹配和样例类"},[":md"]],
  ["v-31ed5c46","/docs/machine-learning/coding/big-data/scala/scala-basis/scala-basis.html",{"title":"Scala基础"},[":md"]],
  ["v-21e1d056","/docs/machine-learning/coding/big-data/scala/scala-introduction/scala-introduction.html",{"title":"Scala简介"},[":md"]],
  ["v-0d625d16","/docs/machine-learning/coding/big-data/spark/mllib/lr.html",{"title":"LR逻辑回归"},[":md"]],
  ["v-344a4d6e","/docs/machine-learning/coding/big-data/spark/mllib/milib.html",{"title":"MLlib机器学习库"},[":md"]],
  ["v-6d085d55","/docs/machine-learning/coding/big-data/spark/pyspark/pyspark.html",{"title":"pyspark"},[":md"]],
  ["v-7c76f859","/docs/machine-learning/coding/big-data/spark/rdd/rdd.html",{"title":"RDD编程"},[":md"]],
  ["v-48b5d8ff","/docs/machine-learning/coding/big-data/spark/spark-introduction/spark-introduction.html",{"title":"Spark简介"},[":md"]],
  ["v-12cc06ce","/docs/machine-learning/coding/big-data/spark/spark-make-tfrecord/spark-make-tfrecord.html",{"title":"利用spark生成tfrecord文件"},[":md"]],
  ["v-180d6262","/docs/machine-learning/coding/cs-courses/compiler-principles/cmake/cmake.html",{"title":"CMake"},[":md"]],
  ["v-f261379a","/docs/machine-learning/coding/cs-courses/compiler-principles/compilation-process-and-link-library/compilation-process-and-link-library.html",{"title":"编译过程、静态库和动态库"},[":md"]],
  ["v-d878e49a","/docs/machine-learning/coding/cs-courses/compiler-principles/extern-c/extern-c.html",{"title":"关于extern \"C\""},[":md"]],
  ["v-1d58a06d","/docs/machine-learning/coding/cs-courses/compiler-principles/gcc-compiler-introduction/gcc-compiler-introduction.html",{"title":"GCC编译器介绍"},[":md"]],
  ["v-61d20733","/docs/machine-learning/coding/cs-courses/compiler-principles/make/make.html",{"title":"Make"},[":md"]],
  ["v-b410be9a","/docs/machine-learning/coding/cs-courses/compiler-principles/qmake/qmake.html",{"title":"QMake生成Makefile"},[":md"]],
  ["v-77735dfe","/docs/machine-learning/coding/cs-courses/computer-network/tcp-ip-protocol-family/tcp-ip-protocol-family.html",{"title":"TCP/IP协议族"},[":md"]],
  ["v-6c1b340d","/docs/machine-learning/coding/cs-courses/computer-organization/embedded-system/embedded-system.html",{"title":"嵌入式系统"},[":md"]],
  ["v-97a88ad4","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/algorithms/algorithms.html",{"title":"算法"},[":md"]],
  ["v-3319eece","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/data-structures/data-structures.html",{"title":"数据结构"},[":md"]],
  ["v-bb27d0e4","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/data-structures-and-algorithms-introduction/data-structures-and-algorithms-introduction.html",{"title":"数据结构与算法概述"},[":md"]],
  ["v-5b1cd1d8","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/jianzhi-offer.html",{"title":"剑指offer"},[":md"]],
  ["v-059ac6b6","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/leetcode/leetcode.html",{"title":"leetcode"},[":md"]],
  ["v-5ebdc7ff","/docs/machine-learning/coding/cs-courses/operating-system/docker/docker.html",{"title":"Docker"},[":md"]],
  ["v-35573855","/docs/machine-learning/coding/cs-courses/operating-system/linux/linux.html",{"title":"Linux"},[":md"]],
  ["v-2c149f83","/docs/machine-learning/coding/programing-language/c__/algorithm-lib/algorithm-lib.html",{"title":"algorithm算法库"},["/docs/machine-learning/coding/programing-language/c++/algorithm-lib/algorithm-lib.html","/docs/machine-learning/coding/programing-language/c++/algorithm-lib/algorithm-lib.md"]],
  ["v-2f34f913","/docs/machine-learning/coding/programing-language/c__/stl-container/stl-container.html",{"title":"STL容器"},["/docs/machine-learning/coding/programing-language/c++/stl-container/stl-container.html","/docs/machine-learning/coding/programing-language/c++/stl-container/stl-container.md"]],
  ["v-d30b435a","/docs/machine-learning/coding/programing-language/c__/tips/tips.html",{"title":"知识点"},["/docs/machine-learning/coding/programing-language/c++/tips/tips.html","/docs/machine-learning/coding/programing-language/c++/tips/tips.md"]],
  ["v-6812169e","/docs/machine-learning/coding/programing-language/python/application/application.html",{"title":"python应用"},[":md"]],
  ["v-15ce09c0","/docs/machine-learning/coding/programing-language/python/cython/cython.html",{"title":"cython"},[":md"]],
  ["v-09a7d330","/docs/machine-learning/coding/programing-language/python/grammar/grammar.html",{"title":"语法"},[":md"]],
  ["v-b9900200","/docs/machine-learning/coding/programing-language/python/introduction/introduction.html",{"title":"python简介"},[":md"]],
  ["v-998373f0","/docs/machine-learning/coding/programing-language/python/library/library.html",{"title":"python库"},[":md"]],
  ["v-c90dcd2a","/docs/machine-learning/coding/programing-language/python/library/matplotlib.html",{"title":"matplotlib"},[":md"]],
  ["v-38eb29b4","/docs/machine-learning/coding/programing-language/python/library/numpy.html",{"title":"NumPy"},[":md"]],
  ["v-2b2f1856","/docs/machine-learning/coding/programing-language/python/library/pandas.html",{"title":"pandas"},[":md"]],
  ["v-6d0bcdfb","/docs/machine-learning/coding/programing-language/python/library/scikit-learn.html",{"title":"scikit-learn"},[":md"]],
  ["v-1bf4447e","/docs/machine-learning/coding/programing-language/python/library/scipy.html",{"title":"scipy"},[":md"]],
  ["v-4c3dc980","/docs/machine-learning/coding/programing-language/python/tips/tips.html",{"title":"知识点"},[":md"]],
  ["v-e47a1ba0","/docs/machine-learning/deep-learning/graph-neural-networks/graph-convolutional-networks/gcn-comprehensive-understand/gcn-comprehensive-understand.html",{"title":"GCN图卷积网络全面理解"},[":md"]],
  ["v-3569fef0","/docs/machine-learning/deep-learning/graph-neural-networks/graph-convolutional-networks/gcn-essential-understand/gcn-essential-understand.html",{"title":"GCN图卷积网络本质理解"},[":md"]],
  ["v-251c0d64","/docs/machine-learning/deep-learning/graph-neural-networks/graph-convolutional-networks/gcn-numpy-fulfillment/gcn-numpy-fulfillment.html",{"title":"GCN图卷积网络的numpy简单实现"},[":md"]],
  ["v-05e47cb0","/docs/machine-learning/deep-learning/graph-neural-networks/graph-convolutional-networks/gcn-preliminary-understand/gcn-preliminary-understand.html",{"title":"GCN图卷积网络初步理解"},[":md"]],
  ["v-7fa3cd8c","/docs/machine-learning/deep-learning/graph-neural-networks/graph-convolutional-networks/graphsage/graphsage.html",{"title":"graphsage"},[":md"]],
  ["v-3bfd93f4","/docs/machine-learning/deep-learning/graph-neural-networks/graph-convolutional-networks/semi-supervised-gcn/SEMI-SUPERVISED-CLASSIFICATION-WITH-GRAPH-CONVOLUTIONAL-NETWORKS.html",{"title":"基于图卷积网络的半监督学习"},[":md"]],
  ["v-fbb795ee","/docs/machine-learning/deep-learning/recurrent-neural-network/long-short-term-memory-networks/long-short-term-memory-networks/long-short-term-memory-networks.html",{"title":"LSTM长短期记忆网络"},[":md"]],
  ["v-4e7a9c7e","/docs/machine-learning/deep-learning/recurrent-neural-network/long-short-term-memory-networks/pix2code/pix2code-Generating-Code-from-a-Graphical-User-Interface-Screenshot.html",{"title":"pix2code"},[":md"]],
  ["v-79fbec06","/docs/machine-learning/deep-learning/tips/normalization/batch-normalization/batch-normalization.html",{"title":"Batch Normalization"},[":md"]],
  ["v-b85716e2","/docs/machine-learning/deep-learning/tips/normalization/layer-normalization/layer-normalization.html",{"title":"Layer Normalization"},[":md"]],
  ["v-ac21292a","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow1.0/basic-concept-analysis/basic-concept-analysis.html",{"title":"TensorFlow基础概念解析"},[":md"]],
  ["v-03ebaa2d","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow1.0/basis/basis.html",{"title":"TensorFlow基础"},[":md"]],
  ["v-db020d3a","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow1.0/cnn/cnn.html",{"title":"基于TenserFlow的目标识别与分类"},[":md"]],
  ["v-e6d2890e","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow1.0/dataset/dataset.html",{"title":"TensorFlow Dataset API"},[":md"]],
  ["v-e007b32a","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow1.0/neural-network/neural-network.html",{"title":"Neural Network"},[":md"]],
  ["v-28e4fee8","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow2.0/basis/basis.html",{"title":"TensorFlow2.0基础"},[":md"]],
  ["v-788cb018","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow2.0/keras/keras.html",{"title":"keras"},[":md"]],
  ["v-22292c48","/docs/machine-learning/machine-learning-framework/tensorflow/tools/ckpt-to-pb/ckpt-to-pb.html",{"title":"TensorFlow中ckpt转pb文件（模型持久化）"},[":md"]],
  ["v-0616055c","/docs/machine-learning/machine-learning-framework/tensorflow/tools/get-weight/get-weight.html",{"title":"得到模型参数值"},[":md"]],
  ["v-15028a62","/docs/machine-learning/machine-learning-framework/tensorflow/tools/gpu/gpu.html",{"title":"Tensorflow中使用GPU"},[":md"]],
  ["v-3bc42c68","/docs/machine-learning/mathematics/gradient-update-algorithm/incremental-learning/lwf/Learning-without-Forgetting.html",{"title":"LwF"},[":md"]],
  ["v-1ada0a21","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/adadelta/adadelta.html",{"title":"Adadelta"},[":md"]],
  ["v-029e4c72","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/adagrad/adagrad.html",{"title":"AdaGrad"},[":md"]],
  ["v-d9988cfe","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/adam/adam.html",{"title":"Adam"},[":md"]],
  ["v-08020de1","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/adamax/adamax.html",{"title":"AdasMax"},[":md"]],
  ["v-75246cb5","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/amsgrad/amsgrad.html",{"title":"AMSGrad"},[":md"]],
  ["v-674c6adb","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/gradient-descent-algorithms-evolution/gradient-descent-algorithms-evolution.html",{"title":"梯度下降算法的演化"},[":md"]],
  ["v-53d66c61","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/momentum/momentum.html",{"title":"Momentum动量法"},[":md"]],
  ["v-a3622436","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/nadam/nadam.html",{"title":"Nadam"},[":md"]],
  ["v-670885e1","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/nesterov/nesterov.html",{"title":"Nesterov牛顿动量法"},[":md"]],
  ["v-40f1fd2e","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/rmsprop/rmsprop.html",{"title":"RMSprop"},[":md"]],
  ["v-026bc7ff","/docs/machine-learning/mathematics/gradient-update-algorithm/offline-learning/sgd/sgd.html",{"title":"随机梯度下降"},[":md"]],
  ["v-78fc681e","/docs/machine-learning/mathematics/gradient-update-algorithm/online-learning/ftrl/ftrl.html",{"title":"FTRL"},[":md"]],
  ["v-aca76b38","/docs/machine-learning/mathematics/numerical-calculation-and-optimization/convex-optimization/convex-optimization-problem/convex-optimization-problem.html",{"title":"凸优化问题"},[":md"]],
  ["v-220a5de0","/docs/machine-learning/mathematics/numerical-calculation-and-optimization/convex-optimization/convex-set-and-convex-function/convex-set-and-convex-function.html",{"title":"凸集和凸函数"},[":md"]],
  ["v-001b4a02","/docs/machine-learning/mathematics/statistics/bayesian-analysis/bayes-probability/bayes-probability.html",{"title":"贝叶斯概率"},[":md"]],
  ["v-24728b7e","/docs/machine-learning/mathematics/statistics/bayesian-analysis/probability-and-bayesian-prior/probability-and-bayesian-prior.html",{"title":"概率论与贝叶斯先验"},[":md"]],
  ["v-688a2835","/docs/machine-learning/mathematics/statistics/bayesian-analysis/conjugate-prior/conjugate-prior.html",{"title":"共轭先验"},[":md"]],
  ["v-a8ca7794","/docs/machine-learning/mathematics/statistics/probability-distribution/beta-distribution/beta-distribution.html",{"title":"Beta贝塔分布"},[":md"]],
  ["v-eb71b6cc","/docs/machine-learning/mathematics/statistics/probability-distribution/dirichlet-distribution/dirichlet-distribution.html",{"title":"Dirichlet狄利克雷分布"},[":md"]],
  ["v-1665237a","/docs/machine-learning/mathematics/statistics/probability-distribution/gamma-distribution/gamma-distribution.html",{"title":"Gamma伽马分布"},[":md"]],
  ["v-445b490c","/docs/machine-learning/mathematics/statistics/probability-distribution/gamma-function/gamma-function.html",{"title":"Gamma伽马函数"},[":md"]],
  ["v-755f64b8","/docs/machine-learning/mathematics/statistics/probability-distribution/normal-distribution/normal-distribution.html",{"title":"Normal正态分布"},[":md"]],
  ["v-cd2938cc","/docs/machine-learning/mathematics/statistics/probability-distribution/student-t-distribution/student-t-distribution.html",{"title":"student-t分布"},[":md"]],
  ["v-d7958dee","/docs/machine-learning/mathematics/statistics/variance-and-covariance/covariance-matrix/covariance-matrix.html",{"title":"协方差矩阵"},[":md"]],
  ["v-11ead915","/docs/machine-learning/mathematics/statistics/variance-and-covariance/sample-variance-unbiased-estimate/sample-variance-unbiased-estimate.html",{"title":"样本方差的无偏估计"},[":md"]],
  ["v-39e38ea7","/docs/machine-learning/mathematics/statistics/variance-and-covariance/welford-algorithm-for-updating-variance/welford-algorithm-for-updating-variance.html",{"title":"Welfor算法：迭代更新方差"},[":md"]],
  ["v-72b930ce","/docs/machine-learning/machine-learning/ensemble-learning/bagging/random-forest/random-forest.html",{"title":"随机森林"},[":md"]],
  ["v-16d4639c","/docs/machine-learning/machine-learning/ensemble-learning/boosting/adaboost/adaboost.html",{"title":"AdaBoost"},[":md"]],
  ["v-99e1f050","/docs/machine-learning/machine-learning/ensemble-learning/boosting/gradient-boosting/gradient-boosting.html",{"title":"Gradient Boosting"},[":md"]],
  ["v-4b190d68","/docs/machine-learning/multimodal-large-model/industry-application/openai/point-e/point-e.html",{"title":"Point-E文本生成3D点云模型"},[":md"]],
  ["v-7ed94960","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/alibaba/alibaba.html",{"title":"阿里巴巴"},[":md"]],
  ["v-4edb8e56","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/baichuan-intelligence/baichuan-intelligence.html",{"title":"百川智能"},[":md"]],
  ["v-219b1892","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/baidu/baidu.html",{"title":"百度"},[":md"]],
  ["v-2e612240","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/blinkdl/blinkdl.html",{"title":"ChatRWKV"},[":md"]],
  ["v-5dc34d6c","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/fudan-university-nlp-group/fudan-university-nlp-group.html",{"title":"复旦大学自然语言处理实验室邱锡鹏团队"},[":md"]],
  ["v-434803ea","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/google/google.html",{"title":"Google"},[":md"]],
  ["v-1290d016","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/hpcaitech/hpcaitech.html",{"title":"HPC-AI Tech"},[":md"]],
  ["v-27d236ea","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/meta/meta.html",{"title":"Meta"},[":md"]],
  ["v-67a73bec","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/openai/openai.html",{"title":"OpenAI"},[":md"]],
  ["v-59b34fda","/docs/machine-learning/natural-language-processing/large-language-model/rlhf/ColossalChat/ColossalChat.html",{"title":"ColossalChat"},[":md"]],
  ["v-796d9e73","/docs/machine-learning/recommender-systems/advanced-knowledge/deep-learning/deepffm/DeepFFM.html",{"title":"DeepFFM"},[":md"]],
  ["v-21da28c8","/docs/machine-learning/recommender-systems/advanced-knowledge/deep-learning/deepfm/DeepFM-A-Factorization-Machine-based-Neural-Network-for-CTR-Prediction.html",{"title":"DeepFM: A Factorization-Machine based Neural Network for CTR Prediction"},[":md"]],
  ["v-7095553a","/docs/machine-learning/recommender-systems/advanced-knowledge/deep-learning/dssm/Learning-Deep-Structured-Semantic-Models-for-Web-Search-using-Clickthrough-Data.html",{"title":"DSSM: Learning Deep Structured Semantic Models for Web Search using Clickthrough Data"},[":md"]],
  ["v-5eaabdfd","/docs/machine-learning/recommender-systems/advanced-knowledge/deep-learning/wide-and-deep/wide-and-deep.html",{"title":"Wide&Deep"},[":md"]],
  ["v-7fd512bc","/docs/machine-learning/recommender-systems/advanced-knowledge/graph-convolutional-network/gcn-web-scale/Graph-Convolutional-Neural-Networks-for-Web-Scale-Recommender-Systems.html",{"title":"用于大规模推荐系统的图卷积神经网络"},[":md"]],
  ["v-dca31a84","/docs/machine-learning/recommender-systems/advanced-knowledge/graph-embedding/graph-embedding-introduction/graph-embedding-introduction.html",{"title":"图表征概述"},[":md"]],
  ["v-3bb2f96e","/docs/machine-learning/recommender-systems/advanced-knowledge/graph-embedding/line/LINE-Large-scale-Information-Network-Embedding.html",{"title":"LINE: Large-scale Information Network Embedding"},[":md"]],
  ["v-2e956208","/docs/machine-learning/recommender-systems/advanced-knowledge/machine-learning/ffm/FFM.html",{"title":"FFM"},[":md"]],
  ["v-3a7bdc1b","/docs/machine-learning/recommender-systems/advanced-knowledge/machine-learning/fm/Factorization-Machines.html",{"title":"Factorization Machines"},[":md"]],
  ["v-a067dc2a","/docs/machine-learning/recommender-systems/advanced-knowledge/reinforcement-learning/drn/DRN-A-Deep-Reinforcement-Learning-Framework-for-News-Recommendation.html",{"title":"DRN: A Deep Reinforcement Learning Framework for News Recommendation"},[":md"]],
  ["v-78f117c9","/docs/machine-learning/recommender-systems/industry-application/alibaba/behavior-sequence-transformer/Behavior-Sequence-Transformer-for-E-commerce-Recommendation-in-Alibaba.html",{"title":"Behavior Sequence Transformer for E-commerce Recommendation in Alibaba"},[":md"]],
  ["v-4a304154","/docs/machine-learning/recommender-systems/industry-application/alibaba/deep-interest-network/Deep-Interest-Network-for-Click-Through-Rate-Prediction.html",{"title":"DIN:Deep Interest Network for Click-Through Rate Prediction"},[":md"]],
  ["v-06558523","/docs/machine-learning/recommender-systems/industry-application/alibaba/deep-session-interest-network/DSIN-Deep-Session-Interest-Network-for-Click-Through-Rate-Prediction.html",{"title":"DSIN:Deep Session Interest Network for Click-Through Rate Prediction"},[":md"]],
  ["v-ae2abdba","/docs/machine-learning/recommender-systems/industry-application/alibaba/esmm/Entire-Space-Multi-Task-Model-An-Effective-Approach-for-Estimating-Post-Click-Conversion-Rate.html",{"title":"ESMM完整空间上的多任务模型"},[":md"]],
  ["v-09bf19e8","/docs/machine-learning/recommender-systems/industry-application/alibaba/tree-based-deep-model/Learning-Tree-based-Deep-Model-for-Recommender-Systems.html",{"title":"TDM:Learning Tree-based Deep Model for Recommender Systems"},[":md"]],
  ["v-4e870071","/docs/machine-learning/recommender-systems/industry-application/facebook/xgboost_lr/Practical-Lessons-from-Predicting-Clicks-on-Ads-at-Facebook.html",{"title":"XGB+LR:Practical Lessons from Predicting Clicks on Ads at Facebook"},["/docs/machine-learning/recommender-systems/industry-application/facebook/xgboost+lr/Practical-Lessons-from-Predicting-Clicks-on-Ads-at-Facebook.html","/docs/machine-learning/recommender-systems/industry-application/facebook/xgboost+lr/Practical-Lessons-from-Predicting-Clicks-on-Ads-at-Facebook.md"]],
  ["v-5fcfddf7","/docs/machine-learning/recommender-systems/industry-application/google/mmoe/Modeling-Task-Relationships-in-Multi-task-Learning-with-Multi-gate-Mixture-of-Experts.html",{"title":"Multi-task Learning with MMoE"},[":md"]],
  ["v-652b0518","/docs/machine-learning/recommender-systems/industry-application/youtube/youtube-dnn/Deep-Neural-Networks-for-YouTube-Recommendations.html",{"title":"YouTubeDNN:Deep Neural Networks for YouTube Recommendations"},[":md"]],
  ["v-c201123a","/docs/machine-learning/reinforcement-learning/imatation-learning/behavior-cloning/paper/paper.html",{"title":"IRL逆强化学习论文"},[":md"]],
  ["v-c9816cea","/docs/machine-learning/reinforcement-learning/imatation-learning/inverse-reinforcement-learning/paper/paper.html",{"title":"IRL逆强化学习论文"},[":md"]],
  ["v-ab9b5872","/docs/machine-learning/reinforcement-learning/imatation-learning/paper/BC_GAIL/Augmenting-GAIL-with-BC-for-sample-effici%20-%20%E5%89%AF%E6%9C%AC.html",{"title":"Augmenting GAIL with BC for sample efficient imitation learning"},["/docs/machine-learning/reinforcement-learning/imatation-learning/paper/BC_GAIL/Augmenting-GAIL-with-BC-for-sample-effici - 副本.html","/docs/machine-learning/reinforcement-learning/imatation-learning/paper/BC+GAIL/Augmenting-GAIL-with-BC-for-sample-effici - 副本.html","/docs/machine-learning/reinforcement-learning/imatation-learning/paper/BC+GAIL/Augmenting-GAIL-with-BC-for-sample-effici%20-%20%E5%89%AF%E6%9C%AC.html","/docs/machine-learning/reinforcement-learning/imatation-learning/paper/BC+GAIL/Augmenting-GAIL-with-BC-for-sample-effici - 副本.md","/docs/machine-learning/reinforcement-learning/imatation-learning/paper/BC+GAIL/Augmenting-GAIL-with-BC-for-sample-effici%20-%20%E5%89%AF%E6%9C%AC.md"]],
  ["v-b7635ea2","/docs/machine-learning/reinforcement-learning/imatation-learning/paper/robotic-table-wiping/Robotic-Table-Wiping-via-Reinforcement-Learning-and-Whole-body-Trajectory-Optimization.html",{"title":"Robotic Table Wiping via Reinforcement Learning and Whole-body Trajectory Optimization"},[":md"]],
  ["v-da929cea","/docs/machine-learning/reinforcement-learning/imatation-learning/paper/sample-complexity/On-the-Sample-Complexity-of-Stability-Constrained-Imitation-Learning.html",{"title":"On the Sample Complexity of Stability Constrained Imitation Learning"},[":md"]],
  ["v-acda85f0","/docs/machine-learning/reinforcement-learning/industry-application/deepmind/alpha-go-zero/Mastering-the-Game-of-Go-without-Human-Knowledge.html",{"title":""},[":md"]],
  ["v-44529826","/docs/machine-learning/reinforcement-learning/industry-application/deepmind/alpha-star/Grandmaster-level-in-StarCraft-II-using-multi-agent-reinforcement-learning.html",{"title":"AlphaStar星际争霸II"},[":md"]],
  ["v-56a52af5","/docs/machine-learning/reinforcement-learning/industry-application/deepmind/alpha-tensor/Discovering-faster-matrix-multiplication-algorithms-with-reinforcement-learning.html",{"title":"AlphaTensor"},[":md"]],
  ["v-204f79a2","/docs/machine-learning/reinforcement-learning/industry-application/inspir-ai/inspir-ai/inspir-ai.html",{"title":"InspirAI启元世界"},[":md"]],
  ["v-47cc1890","/docs/machine-learning/reinforcement-learning/industry-application/inspir-ai/time-chamber/time-chamber.html",{"title":"TimeChamber: A Massively Parallel Large Scale Self-Play Framework"},[":md"]],
  ["v-54bccd4c","/docs/machine-learning/reinforcement-learning/industry-application/openai/oepnai-five/openai-five.html",{"title":"OpenAI Five: Dota 2 with Large Scale Deep Reinforcement Learning 2019"},[":md"]],
  ["v-3485f886","/docs/machine-learning/reinforcement-learning/industry-application/tencent/honor-of-kings/honor-of-kings.html",{"title":"王者荣耀"},[":md"]],
  ["v-420012ee","/docs/machine-learning/reinforcement-learning/multi-agent-reinforcement-learning/paper/mean-field/Mean-Field-Multi-Agent-Reinforcement-Learning.html",{"title":"平均场多智能体强化学习"},[":md"]],
  ["v-3a84c89d","/docs/machine-learning/reinforcement-learning/reinforcement-learning/paper/ddpg/ddpg.html",{"title":"DDPG"},[":md"]],
  ["v-e138bd5e","/docs/machine-learning/reinforcement-learning/reinforcement-learning/paper/ppo/Proximal-Policy-Optimization.html",{"title":"PPO近端策略优化"},[":md"]],
  ["v-92f8e85e","/docs/machine-learning/reinforcement-learning/reinforcement-learning/state-reward-action/reward/reward.html",{"title":"奖励"},[":md"]],
  ["v-305bcb80","/docs/machine-learning/reinforcement-learning/sim2real/paper/i-sim2real/i-Sim2Real-Reinforcement-Learning-of-Robotic-Policies-in-Tight-Human-Robot-Interaction-Loops.html",{"title":"i-Sim2Real: Reinforcement Learning of Robotic Policies in Tight Human-Robot Interaction Loops"},[":md"]],
  ["v-182b7fe6","/docs/machine-learning/reinforcement-learning/sim2real/paper/legged-robots-keep-on-learning/Legged-Robots-that-Keep-on-Learning-Fine-Tuning-Locomotion-Policies-in-the-Real-World.html",{"title":"Legged Robots that Keep on Learning: Fine-Tuning Locomotion Policies in the Real World"},[":md"]],
  ["v-0423b716","/docs/machine-learning/artificial-general-intelligence/autopilot/control/llm-based-control/PaLM-E/PaLM-E.html",{"title":"PaLM-E: An Embodied Multimodal Language Model"},[":md"]],
  ["v-a9e3e588","/docs/machine-learning/artificial-general-intelligence/autopilot/control/llm-based-control/chatGPT-for-robotics/ChatGPT-for-Robotics-Design-Principles-and-Model-Abilities.html",{"title":"ChatGPT for Robotics: Design Principles and Model Abilities"},[":md"]],
  ["v-1bb92d3d","/docs/machine-learning/artificial-general-intelligence/autopilot/control/llm-based-control/code-as-policies/Code-as-Policies-Language-Model-Programs-for-Embodied-Control.html",{"title":"Code as Policies: Language Model Programs for Embodied Control"},[":md"]],
  ["v-e36ee98a","/docs/machine-learning/artificial-general-intelligence/autopilot/control/llm-based-control/performer-mpc/Learning-Model-Predictive-Controllers-with-Real-Time-Attention-for-Real-World-Navigation.html",{"title":""},[":md"]],
  ["v-2c887d0a","/docs/machine-learning/artificial-general-intelligence/autopilot/control/llm-based-control/rt-1/RT-1-Robotics-Transformer-for-Real-World-Control-at-Scale.html",{"title":"RT-1: Robotics Transformer for Real-World Control at Scale"},[":md"]],
  ["v-2fd8175c","/docs/machine-learning/artificial-general-intelligence/autopilot/control/llm-based-control/towards-robotics-foundation-model/towards-robotics-foundation-model.html",{"title":"Towards a Robotics Foundation Model"},[":md"]],
  ["v-2ef149ca","/docs/machine-learning/artificial-general-intelligence/autopilot/control/pid-control/sqrt-controller/sqrt-controller.html",{"title":"开方控制器sqrt-controller"},[":md"]],
  ["v-2d5e3f9e","/docs/machine-learning/artificial-general-intelligence/autopilot/dynamic-model/aerodynamics/entropy/entropy.html",{"title":"熵"},[":md"]],
  ["v-5bcf4ec5","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/dynamic-system/ESC/ESC.html",{"title":"电调"},[":md"]],
  ["v-202c1685","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/dynamic-system/motor/motor.html",{"title":"电机"},[":md"]],
  ["v-ea65486a","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/accelerometer/accelerometer.html",{"title":"加速度计"},[":md"]],
  ["v-67be830b","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/airspeed_meter/airspeed_meter.html",{"title":"空速计"},[":md"]],
  ["v-4b773faf","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/ammeter/ammeter.html",{"title":"电流计"},[":md"]],
  ["v-4cb19b42","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/gyroscope/gyroscope.html",{"title":"陀螺仪"},[":md"]],
  ["v-f030a32a","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/magnetometer/magnetometer.html",{"title":"磁力计"},[":md"]],
  ["v-357c8900","/docs/machine-learning/artificial-general-intelligence/autopilot/planning/llm-based-planning/inner-monologue/Inner-Monologue-Embodied-Reasoning-through-Planning-with-Language-Models.html",{"title":"Inner Monologue: Embodied Reasoning through Planning with Language Models"},[":md"]],
  ["v-05c30b71","/docs/machine-learning/artificial-general-intelligence/autopilot/planning/llm-based-planning/interactive-language/Inner-Monologue-Embodied-Reasoning-through-Planning-with-Language-Models.html",{"title":"Inner Monologue: Embodied Reasoning through Planning with Language Models"},[":md"]],
  ["v-13e90aaa","/docs/machine-learning/artificial-general-intelligence/autopilot/planning/llm-based-planning/interactive-language/Interactive-Language-Talking-to-Robots-in-Real-Time.html",{"title":"Interactive-Language-Talking-to-Robots-in-Real-Time"},[":md"]],
  ["v-59eec5c4","/docs/machine-learning/artificial-general-intelligence/autopilot/planning/llm-based-planning/socratic-models/Socratic-Models-Composing-Zero-Shot-Multimodal-Reasoning-with-Language.html",{"title":"Socratic Models: Composing Zero-Shot Multimodal Reasoning with Language"},[":md"]],
  ["v-04121223","/docs/machine-learning/artificial-general-intelligence/autopilot/planning/llm-based-planning/towards-helpful-robots-grounding/Towards-Helpful-Robots-Grounding-Language-in-Robotic-Affordances.html",{"title":"Towards Helpful Robots: Grounding Language in Robotic Affordances"},[":md"]],
  ["v-df4a35c2","/docs/machine-learning/artificial-general-intelligence/autopilot/planning/llm-based-planning/value-function-spaces/Value-Function-Spaces-Skill-Centric-State-Abstractions-for-Long-Horizon-Reasoning.html",{"title":"Value Function Spaces: Skill-Centric State Abstractions for Long-Horizon Reasoning"},[":md"]],
  ["v-6bad8c7c","/docs/machine-learning/coding/cs-courses/computer-network/tcp-ip-protocol-family/tcp/tcp.html",{"title":"TCP通信"},[":md"]],
  ["v-0c34d731","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/algorithms/dynamic-programming/dynamic-programming.html",{"title":"动态规划"},[":md"]],
  ["v-14686dfa","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/algorithms/recursion/recursion.html",{"title":"递归"},[":md"]],
  ["v-5823808c","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/algorithms/sort/heap-sort.html",{"title":"堆排序"},[":md"]],
  ["v-2e4a8898","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/algorithms/sort/merge-sort.html",{"title":"归并排序"},[":md"]],
  ["v-6a1f5f29","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/algorithms/sort/quick-sort.html",{"title":"快速排序"},[":md"]],
  ["v-c97304ee","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/algorithms/sort/sort.html",{"title":"排序"},[":md"]],
  ["v-70bec6c2","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/data-structures/priority-queue/priority-queue.html",{"title":"优先级队列"},[":md"]],
  ["v-5b6f1c42","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/data-structures/tree/tree.html",{"title":"树"},[":md"]],
  ["v-517a4df3","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/array/array.html",{"title":"数组"},[":md"]],
  ["v-59526191","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/binary-tree/binary-tree.html",{"title":"二叉树"},[":md"]],
  ["v-169eb18f","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/dynamic-programming/dynamic-programming.html",{"title":"动态规划"},[":md"]],
  ["v-efb55f32","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/list/list.html",{"title":"链表"},[":md"]],
  ["v-8f211472","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/others/others.html",{"title":"其他"},[":md"]],
  ["v-68dfd16d","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/recursion-and-back-tracking/recursion-and-back-tracking.html",{"title":"递归和回溯法"},[":md"]],
  ["v-06f193b9","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/stack-and-queue/stack-and-queue.html",{"title":"栈和队列"},[":md"]],
  ["v-21ec9d87","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/jianzhi-offer/string/string.html",{"title":"字符串"},[":md"]],
  ["v-99d87040","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/leetcode/dynamic-programming/dynamic-programming.html",{"title":"动态规划"},[":md"]],
  ["v-58b79e54","/docs/machine-learning/coding/cs-courses/operating-system/linux/linux-command/linux-command.html",{"title":"Linux常用命令"},[":md"]],
  ["v-7271573e","/docs/machine-learning/coding/cs-courses/operating-system/linux/linux-communication/linux-communication.html",{"title":"Linux通信"},[":md"]],
  ["v-4ed4bb7a","/docs/machine-learning/coding/cs-courses/operating-system/linux/linux-system/linux-system.html",{"title":"linux系统安装"},[":md"]],
  ["v-43b811d8","/docs/machine-learning/coding/cs-courses/operating-system/linux/shell/shell.html",{"title":"shell编程"},[":md"]],
  ["v-70542344","/docs/machine-learning/coding/cs-courses/operating-system/linux/vim/vim.html",{"title":"vim编辑器"},[":md"]],
  ["v-5340ee10","/docs/machine-learning/coding/programing-language/c__/tips/string/string.html",{"title":"string字符串类"},["/docs/machine-learning/coding/programing-language/c++/tips/string/string.html","/docs/machine-learning/coding/programing-language/c++/tips/string/string.md"]],
  ["v-43a3351f","/docs/machine-learning/coding/programing-language/python/application/sort/sort.html",{"title":"排序"},[":md"]],
  ["v-46bb8f2c","/docs/machine-learning/coding/programing-language/python/grammar/basis/basis.html",{"title":"基础语法"},[":md"]],
  ["v-208b19f6","/docs/machine-learning/coding/programing-language/python/grammar/class/class.html",{"title":"类和对象"},[":md"]],
  ["v-2f05fd68","/docs/machine-learning/coding/programing-language/python/grammar/data-structure/data-structure.html",{"title":"数据结构"},[":md"]],
  ["v-f9267bb0","/docs/machine-learning/coding/programing-language/python/grammar/file/file.html",{"title":"文件操作"},[":md"]],
  ["v-3996a3b0","/docs/machine-learning/coding/programing-language/python/grammar/function/function.html",{"title":"函数"},[":md"]],
  ["v-2b770030","/docs/machine-learning/coding/programing-language/python/grammar/process-control/process-control.html",{"title":"过程控制"},[":md"]],
  ["v-79aa2b88","/docs/machine-learning/coding/programing-language/python/grammar/regular-expression/regular-expression.html",{"title":"正则表达式"},[":md"]],
  ["v-563b21ed","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow2.0/keras/keras-metrics/keras-metrics.html",{"title":"指标keras.metrics"},[":md"]],
  ["v-6b18efc9","/docs/machine-learning/machine-learning-framework/tensorflow/tensorflow2.0/keras/keras-optimizer/keras-optimizer.html",{"title":"优化器keras.optimizer"},[":md"]],
  ["v-31bd4685","/docs/machine-learning/machine-learning/ensemble-learning/boosting/gradient-boosting/gbdt/gbdt.html",{"title":"GBDT"},[":md"]],
  ["v-473d28ed","/docs/machine-learning/machine-learning/ensemble-learning/boosting/gradient-boosting/light-gbm/light-gbm.html",{"title":"lightGBM"},[":md"]],
  ["v-93fe5a0a","/docs/machine-learning/machine-learning/ensemble-learning/boosting/gradient-boosting/xgboost/xgboost.html",{"title":"XGBoost"},[":md"]],
  ["v-3917091d","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/alibaba/gpt3-chinese/gpt3-chinese.html",{"title":"中文GPT-3"},[":md"]],
  ["v-7cd776d8","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/baichuan-intelligence/baichuan-7B/baichuan-7B.html",{"title":"baichuan-7B"},[":md"]],
  ["v-5f51ae4e","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/baidu/ERNIE-Bot/ERNIE-Bot.html",{"title":"ERNIE-Bot文心一言"},[":md"]],
  ["v-4c34f3d6","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/blinkdl/ChatRWKV/ChatRWKV.html",{"title":"ChatRWKV"},[":md"]],
  ["v-1575f76e","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/fudan-university-nlp-group/moss/moss.html",{"title":"MOSS"},[":md"]],
  ["v-6ae79100","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/google/Bard/Bard.html",{"title":"Bard"},[":md"]],
  ["v-f4570b26","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/hpcaitech/colossal-ai/ColossalAI.html",{"title":"ColossalAI"},[":md"]],
  ["v-2f48fde8","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/meta/LLaMa/LLaMa.html",{"title":"LLaMa"},[":md"]],
  ["v-e8b7cda8","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/meta/opt/opt.html",{"title":"OPT复现开源GPT3"},[":md"]],
  ["v-566a369f","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/openai/ChatGPT/ChatGPT.html",{"title":"ChatGPT"},[":md"]],
  ["v-7e46db61","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/openai/GPT-4/GPT-4.html",{"title":"GPT-4"},[":md"]],
  ["v-fe9d3b2e","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/openai/gpt-series-introduction/gpt-series-introduction.html",{"title":"GTP系列介绍"},[":md"]],
  ["v-33b5b303","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/openai/unsupervised-sentiment-neuron/unsupervised-sentiment-neuron.html",{"title":"Unsupervised Sentiment Neuron"},[":md"]],
  ["v-019f9292","/docs/machine-learning/reinforcement-learning/imatation-learning/behavior-cloning/paper/goals-eye/GoalsEye-Learning-High-Speed-Precision-Table-Tennis-on-a-Physical-Robot.html",{"title":"GoalsEye: Learning High Speed Precision Table Tennis on a Physical Robot"},[":md"]],
  ["v-1489d925","/docs/machine-learning/reinforcement-learning/imatation-learning/behavior-cloning/paper/visual-backtracking-teleoperation/Visual-Backtracking-Teleoperation-A-Data-Collection-Proto.html",{"title":"Visual Backtracking Teleoperation: A Data Collection Protocol for Offline Image-Based Reinforcement Learning"},[":md"]],
  ["v-05612514","/docs/machine-learning/reinforcement-learning/imatation-learning/inverse-reinforcement-learning/paper/xirl/xirl-cross-embodiment-inverse-reinforcement-learning.html",{"title":"XIRL: Cross-embodiment Inverse Reinforcement Learning"},[":md"]],
  ["v-e87b33b2","/docs/machine-learning/reinforcement-learning/industry-application/inspir-ai/time-chamber/humanoid-strike/humanoid-strike.html",{"title":"Humanoid Strike"},[":md"]],
  ["v-5d6a322d","/docs/machine-learning/reinforcement-learning/industry-application/inspir-ai/time-chamber/time-chamber/time-chamber.html",{"title":"TimeChamber: A Massively Parallel Large Scale Self-Play Framework"},[":md"]],
  ["v-3c9136eb","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/dynamic-system/ESC/thrust2pwm_curve/thrust2pwm_curve.html",{"title":"螺旋桨推力与转速的关系"},[":md"]],
  ["v-2ff42bfe","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/dynamic-system/motor/motor-principle/motor-principle.html",{"title":"电机的原理"},[":md"]],
  ["v-1e168bcb","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/accelerometer/accelerometer-six-sided-calibration-method/accelerometer-six-sided-calibration-method.html",{"title":"加速度计的六面校准法"},[":md"]],
  ["v-40b44891","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/ammeter/measure-voltage-for-compensation-to-pwm/measure-voltage-for-compensation-to-pwm.html",{"title":"通过电流计测量电池电动势用于pwm压降补偿"},[":md"]],
  ["v-59e1eaa2","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/gyroscope/gyroscope-calibration/gyroscope-calibration.html",{"title":"陀螺仪校准"},[":md"]],
  ["v-fbd23398","/docs/machine-learning/artificial-general-intelligence/autopilot/electromechanical-systems/sensors/magnetometer/magnetometer-calibration/magnetometer-calibration.html",{"title":"磁力计校准"},[":md"]],
  ["v-91a554ba","/docs/machine-learning/coding/cs-courses/data-structures-and-algorithms/data-structures/tree/avl-tree/avl-tree.html",{"title":"AVL树"},[":md"]],
  ["v-4c4fdfbb","/docs/machine-learning/coding/cs-courses/operating-system/linux/shell/basis/basis.html",{"title":"shell基础"},[":md"]],
  ["v-8e3941be","/docs/machine-learning/coding/cs-courses/operating-system/linux/shell/command/command.html",{"title":"命令"},[":md"]],
  ["v-4c86674e","/docs/machine-learning/coding/cs-courses/operating-system/linux/shell/input_output_redirection/input_output_redirection.html",{"title":"输入/输出重定向"},[":md"]],
  ["v-f403568e","/docs/machine-learning/coding/cs-courses/operating-system/linux/shell/process-control/process-control.html",{"title":"流程控制"},[":md"]],
  ["v-23faec39","/docs/machine-learning/coding/cs-courses/operating-system/linux/shell/variable/variable.html",{"title":"变量"},[":md"]],
  ["v-154a71c0","/docs/machine-learning/machine-learning/ensemble-learning/boosting/gradient-boosting/xgboost/xgboost-practice/xgboost-practice.html",{"title":"XGBoost实践"},[":md"]],
  ["v-57128340","/docs/machine-learning/machine-learning/ensemble-learning/boosting/gradient-boosting/xgboost/xgboost-theory/xgboost-theory.html",{"title":"XGBoost理论"},[":md"]],
  ["v-152a21c5","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/openai/unsupervised-sentiment-neuron/paper/Learning-to-Generate-Reviews.html",{"title":"Learning to Generate Reviews and Discovering Sentiment"},[":md"]],
  ["v-147031f1","/docs/machine-learning/natural-language-processing/large-language-model/industry-application/openai/unsupervised-sentiment-neuron/unsupervised-sentiment-neuron/unsupervised-sentiment-neuron.html",{"title":"Unsupervised Sentiment Neuron"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
